# 项目应用配置
project:
  # 项目应用名称
  project-name: ginyi-admin-demo
  # 项目应用作者
  project-author: ginyi@aliyun.com
  # 项目应用版本
  project-version: 1.0.0
  # 项目应用描述
  project-description: 随便写点什么儿~




# admin端的配置
swagger:
  # 接口文档url
  swagger-url: 写点什么呢~~~
  # 接口文档标题
  swagger-title: Ginyi-admin api doc
  # 接口文档版本号
  swaggerversion: 1.0
  # 接口文档描述
  swagger-description: This is a api doc of Ginyi
  # 接口文档基本包
  swagger-base-package: ginyi.server.web
  # 联系方式
  swagger-contact:
    name: Author Email is Ginyi@aliyun.com
    email: Ginyi@aliyun.com



# 应用服务
server:
  # 服务端口
  port: 8066
  servlet:
    # 应用访问的路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100



spring:
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # 数据源
  datasource:
    type: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceWrapper
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3307/ginyi-spring-vue?serverTimezone=UTC
      username: root
      password: 123456
  # redis 配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为 6379
    port: 6666
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# MyBatis-plus配置
mybatis-plus:
  # mapper.xml文件的位置
  mapper-locations: classpath:mapper/**/*Mapper.xml
  # 类型别名的位置
  type-aliases-package: ginyi.server.**.dto
  configuration:
    # 控制台输出sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl