# web端的配置
swagger:
  base:
    package-web: ginyi.server.admin
    package-admin: ginyi.server.web
  contact:
    email: Ginyi@aliyun.com
    name: 'Author Email is Ginyi@aliyun.com'
  title: 'Ginyi-web api doc'
  description: 'This is a api doc of Ginyi'
  url: '写点什么呢~~~'
  version: 1.0

