server:
  port: 8055
  servlet:
    context-path: /
    tomcat:
      max-swallow-size: -1


project-info:
  project-name: 'ginyi-web-demo'
  project-author: 'ginyi@aliyun.com'
  project-description: '随便写点什么儿~'
  project-version: '@project.version@'

# web端的配置
swagger:
  # 接口文档标题
  title: 'Ginyi-web api doc'
  # 接口文档描述
  description: 'This is a api doc of Ginyi'
  # 基本包
  base:
    package: ginyi.server.web
  # 联系方式
  contact:
    name: 'Author Email is Ginyi@aliyun.com'
    email: Ginyi@aliyun.com
  url: '写点什么呢~~~'
  version: 1.0




spring:
  mvc:
    pathmatch:
      # swagger文档需要该配置
      matching-strategy: ant_path_matcher
  # 数据源
  datasource:
    type: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceWrapper
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3307/reggie?serverTimezone=UTC
      username: root
      password: 123456
  # 使用redis作为缓存
  cache:
    redis:
      time-to-live: 180000
  redis:
    host: localhost
    port: 6666
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 1000

